### ISSUE TITLE
Add Feature Photo Editor into Composer View

### ISSUE THREAD

**Issue by tagmetag** [feedgit/FTiOS#104]
Add Feature Photo Editor into Composer View by using Third-Party. Choose one of these below Third-Parties

- https://github.com/muukii/Pixel
- https://github.com/burhanrashid52/PhotoEditor

![image](https://user-images.githubusercontent.com/19923843/51512654-9f887480-1e39-11e9-8062-d2d4b48adff1.png)

**Comment by kenz68** [comment]
@feedgit support edit in composer photo, touch photo to open edit screen

**Comment by tagmetag** [comment]
Please support **Edit button** to complete this issue

**Comment by kenz68** [comment]
@feedgit please check
