### ISSUE TITLE
Implement Feed for Single Profile Feed View

### ISSUE THREAD

**Issue by tagmetag** [feedgit/FTiOS#105]
1. In single Profile Feed View, change navbar into Text with options:
- **Home**
- **Photos**
- **Videos**
- **About**
- **Blogs**
- **Checkin**

![image](https://user-images.githubusercontent.com/19923843/51518556-e6359900-1e50-11e9-99f2-4c3e69276dac.png)

2. In  **Home** View, get Feed posted by User

Request `GET /api/v1/feed/?user__username={{USERNAME}}"`

![image](https://user-images.githubusercontent.com/19923843/51518630-2432bd00-1e51-11e9-98cc-c897b98f40fc.png)

**Comment by tagmetag** [comment]
@pociosx  Filter user by adding params `{ user__username: duongnuhabang }`

**Comment by pociosx** [comment]
<img width="331" alt="screen shot 2019-03-04 at 9 32 30 pm" src="https://user-images.githubusercontent.com/11501981/53739741-1a2ac200-3ec5-11e9-9aab-13b8e1b3cdbf.png">
@feedgit please check Blog API: https://api.feedtrue.com/api/v1/blog/?user__username=duongnuhabang
return wrong  data for selected user
