### ISSUE TITLE
Change all Composer API into ONE

### ISSUE THREAD

**Issue by tagmetag** [feedgit/FTiOS#109]
Change API composer into ONE:

## Request URL
`POST /api/v1/composer/`

<img width="299" alt="screen shot 2019-01-26 at 9 47 13 pm" src="https://user-images.githubusercontent.com/19923843/51788730-0b5d3b00-21b4-11e9-992d-cd3f5b624a19.png">

## General Request:

- `feed_text`: 1 - 200 limit
- `privacy`: `((0, 'Public'), (1, 'Private'), (2, 'Followers'))`
- `category`: `((0, 'Something'), (1, 'Travel Checkin'), (2, 'Food Review'), (3, 'Review something'))`
- `location.long`
- `location.lat`
- `location.name`
- `location.thumbnail`: ONE file
- `location.type`: Multi allowed
- `location.address`
- `location.description`

![image](https://user-images.githubusercontent.com/19923843/51897986-85730700-23e2-11e9-9ef1-20776c60f541.png)

If Photo composer, request photo
- `photo.image_file`: Multiple allowed

If Video composer, request photo
- `video.video_file`: ONE allowed, Required
- `video.title`: Required
- `video.duration`: Not required

If Blog composer, request photo
- `blog.title`
- `blog.thumbnail`
- `blog.content`

**Comment by kenz68** [comment]
implement composer video/blog in another tasks #113 #114
