### ISSUE TITLE
Split App Icons into 2 types (Active and Unactive)

### ISSUE THREAD

**Issue by tagmetag** [feedgit/FTiOS#11]
Split App Icons into 2 types.

- Bottom Navigator: When **screen active**, icon which respectively navigate to screen **also active**. Library: https://drive.google.com/drive/u/0/folders/1LSvZqxqm5UezNQv8YlVUfYFdUMdXK1VS

**Comment by kenz68** [comment]
[
<img width="419" alt="screen shot 2018-09-07 at 3 09 01 pm" src="https://user-images.githubusercontent.com/11501981/45206787-21736900-b2b0-11e8-9078-19dcf9889d7c.png">
](url)

@feedgit please test
