### ISSUE TITLE
Callback location data in Composer Cell

### ISSUE THREAD

**Issue by tagmetag** [feedgit/FTiOS#111]
1. Callback location data in Composer Cell
![image](https://user-images.githubusercontent.com/19923843/52760572-a5413680-3042-11e9-9a33-f65a03bd35d6.png)

- Inorder to change selected location, touch to this cell then go to **Location Search View**.
- InOrder to remove selected location, touch to button **X**

2. Remove Location in Media Cell

![image](https://user-images.githubusercontent.com/19923843/52760512-5abfba00-3042-11e9-9e0d-85dee5015c52.png)

**Comment by kenz68** [comment]
@feedgit please check search API: https://api.feedtrue.com/api/v1/location/?q=Ho chi min/
