### ISSUE TITLE
Add Categories Selection in Composer

### ISSUE THREAD

**Issue by tagmetag** [feedgit/FTiOS#112]
Add **Categories selection** in composer, which can select from a List View

![image](https://user-images.githubusercontent.com/19923843/52760753-3d3f2000-3043-11e9-9a00-94864902074e.png)

Array for data:

```
let feed_categories = [
  { key: 0, label: 'Something', icon: 'explore-app', background: '#05c8f3', description: 'Something about your life' },
  { key: 1, label: 'Travel Checkin', icon: 'checkin-app', background: '#ffc65c', description: 'Photos of your trip, your travel experience' },
  { key: 2, label: 'Food Review', icon: 'food-app', background: '#ea7878', description: 'Photos of your food, your food experience' }
]
```

When Post a new Feed, append into FormData key `category` with selected **KEY**. Example: `FormData.append('category', 1)`

**Comment by kenz68** [comment]
@feedgit please upload image for 'explore-app',  'checkin-app' and 'food-app'
