### ISSUE TITLE
Edit Profile Screen: Tăng khoảng cách các dòng

### ISSUE THREAD

**Issue by tagmetag** [feedgit/FTiOS#12]
Phần Edit Profile Screen khoảng cách các dòng còn quá gần. 
- Tăng padding và fontsize lên!
- Cho thêm phần username vô đây, có thể sửa username luôn. Tuy nhiên, việc thay đổi username sẽ cần một request với API url khác.

**Comment by kenz68** [comment]
@feedgit please add edit username API

**Comment by tagmetag** [comment]
@pociosx Use old URL https://feedtrue.com/api/v1/users/account/edit/
