### ISSUE TITLE
Edit Profile: Change Ui

### ISSUE THREAD

**Issue by tagmetag** [feedgit/FTiOS#14]
1. Add Field
- Gender: Change style options like Instagram
- Date of Birth: Change style options
- Add Phone Number field.
- Add nickname
- Add quotes
- Add about
- Add bio

2. Push into new Screen: Username, Intro, About, quotes, Bio

3. Add User Avatar - Options: Remove current, Choose Library, Take photo

**Comment by kenz68** [comment]
3. Add User Avatar - Options: Remove current, Choose Library, Take photo
duplicated with #24
