### ISSUE TITLE
FEED: Button more with options

### ISSUE THREAD

**Issue by tagmetag** [feedgit/FTiOS#19]
With 2 case: Case 2 is high level of Case 1

1.  **Case 1**: If `feed.editable = false` (Case feed owner is not request user), user can be get into these actions:

- `Go to feed`: Change screen into `FEED DETAIL`
- `Share`: Open Share Feed Modal
- `See less content`: Temporarily open modal: "You wont see this content anymore" and **remove this feed out of feed list**.
- `Report inapproriate`: Temporarily open modal: "Successfully reported" and **remove this feed out of feed list**.

2.  If `feed.editable = true` (Case feed owner is request user), use can EDIT and DELETE this feed

- 4 options above.
- `Edit`: Open modal Edit
- `Permanently Delete`: (with text-color Red): `DELETE /f/${feedID}/delete/` and **remove this feed out of feed list**

**Comment by kenz68** [comment]
@feedgit added UI and delete action
