### ISSUE TITLE
[REACTION BAR] Thay đổi Icon & Implement API

### ISSUE THREAD

**Issue by tagmetag** [feedgit/FTiOS#26]
- Thay đổi các icon https://drive.google.com/drive/u/0/folders/1qRboD3EvOy5voWpiabZvCPR1teYNFoUM

- Implement API theo [Documentation](https://github.com/feedgit/FTiOS/wiki/Reaction-API-Document)

**Comment by kenz68** [comment]
@feedgit duplicated with #20 ?
