### ISSUE TITLE
UI: Remove button Use without Login

### ISSUE THREAD

**Issue by tagmetag** [feedgit/FTiOS#52]
1. Remove button Use without Login and vertically align middle items

![44633261_333488037216173_2451351364421287936_n](https://user-images.githubusercontent.com/19923843/47283985-b4255880-d60f-11e8-8ec1-75992dce6a9c.jpg)

2. Change First View is Home Page, not Login Page

**Comment by kenz68** [comment]
@feedgit what is API load feed without login?

**Comment by tagmetag** [comment]
@pociosx   load feed without login is sending request with no Authorization JWT Token in Header.
