### ISSUE TITLE
Tính năng Log Out

### ISSUE THREAD

**Issue by tagmetag** [feedgit/FTiOS#6]
Tạo tính năng `Log out` để test Auth

**Comment by kenz68** [comment]
supported logout in setting tab
@feedgit please help to check

**Comment by tagmetag** [comment]
Display: Temporarily display as a **vertical list Menu** like Facebook
<img width="148" alt="screen shot 2018-09-08 at 10 12 17 am" src="https://user-images.githubusercontent.com/19923843/45249743-b11c2480-b34f-11e8-94bb-ce3fc62bf93c.png">
