### ISSUE TITLE
Change UI for PhotoSet in Feed

### ISSUE THREAD

**Issue by tagmetag** [feedgit/FTiOS#74]
Limit 9 photos can be uploaded. Use `Switch Case` Change UI for PhotoSet in Feed

- switch have only **ONE Photo** in photoset: Display Normal, full width and Full Height, but **limit Max height = Width**
- switch have **more than ONE Photo** in photoset. Display into 3 photos in a row (Width = Height), limit 3 rows.

![img_5335](https://user-images.githubusercontent.com/19923843/48330937-10b0ec00-e681-11e8-9dd1-e655318a5c46.PNG)
![img_5336](https://user-images.githubusercontent.com/19923843/48330938-11498280-e681-11e8-880d-409cf6b8e283.PNG)
![img_5337](https://user-images.githubusercontent.com/19923843/48330939-11498280-e681-11e8-8c67-a41d54d6b7fd.PNG)

**Comment by kenz68** [comment]
@feedgit How about max width?
