### ISSUE TITLE
Recolor UI for Video List Screen

### ISSUE THREAD

**Issue by tagmetag** [feedgit/FTiOS#75]
1. Decrease padding in wrapper
2. Decrease gap between Video cell
3. Change color for background: `#dedede`
4. Remove **Play button** in Video Cell
5. Increase Text Indent of Title
6. Add line below Title, color `#f9f9f9`
7. Create border radius for Video cell

![img_5338](https://user-images.githubusercontent.com/19923843/48331520-f415b380-e682-11e8-8c09-81ba4c591021.png)

**Comment by kenz68** [comment]
@feedgit please verify
