### ISSUE TITLE
Bỏ button Done trong Profile Edit khi không thay đổi

### ISSUE THREAD

**Issue by tagmetag** [feedgit/FTiOS#8]
Bỏ button Done trong `Profile Edit` khi không thay đổi.

- Đổi nút `Done` bằng nút `Save`

- Khi đang thay đổi một field trong `Profile Edit` thì nút `Save` xuất hiện cho phép Save field đó

**Comment by kenz68** [comment]
@feedgit please help to test

**Comment by tagmetag** [comment]
When Save process **newly** successes, it's not work.

**Comment by kenz68** [comment]
@feedgit fixed

**Comment by tagmetag** [comment]
@pociosx When touch Edit button, App crash!

**Comment by kenz68** [comment]
@feedgit fixed crash
/about/ API not work, please help to check
