### ISSUE TITLE
Create UI Chat Message List

### ISSUE THREAD

**Issue by tagmetag** [feedgit/FTiOS#86]
Create UI Chat Message List support Infinite Load

`GET /api/v1/chat/contact/`

Add text below `with_user` name (get `room.last_message`)

<img width="457" alt="screen shot 2018-12-06 at 3 14 53 pm" src="https://user-images.githubusercontent.com/19923843/49570607-b34f4880-f969-11e8-9db0-f1331c223538.png">

**Comment by kenz68** [comment]
@feedgit please upload setting icon
