### ISSUE TITLE
Đăng nhập bằng ứng dụng Facebook không thành công

### ISSUE THREAD

**Issue by tagmetag** [feedgit/FTiOS#9]
`Đăng nhập bằng số điện thoại hoặc email` thành công. Tuy nhiên `Đăng nhập bằng ứng dụng Facebook` không thành công
![40946741_353178378754838_3301116291816882176_n](https://user-images.githubusercontent.com/19923843/45104362-258e7200-b15c-11e8-8d3e-5b1c03b0ea62.jpg)

**Comment by kenz68** [comment]
@feedgit fixed, please help to check
