### ISSUE TITLE
Get Video Detail API & Change Video Detail UI

### ISSUE THREAD

**Issue by tagmetag** [feedgit/FTiOS#91]
1. Get Video Detail by using http method with UID:

`GET https://api.feedtrue.com/api/v1/media/video/xmbmwhj5eo/`

2. Change UI of Video

![image](https://user-images.githubusercontent.com/19923843/50331687-2643ec00-0532-11e9-9d16-611712fad345.png)

**Comment by kenz68** [comment]
@feedgit please upload some icons with white color for that screen

**Comment by tagmetag** [comment]
@pociosx Ok soon, copy icon with Black color first into file with name for White color and leave it
