### ISSUE TITLE
Change Top Navigator in Feed View

### ISSUE THREAD

**Issue by tagmetag** [feedgit/FTiOS#97]
1. Remove existed Top Navigator

![image](https://user-images.githubusercontent.com/19923843/50951987-a4683280-14e1-11e9-88e9-f75ced3476fc.png)

2. Change new Top Navigator (Following, Hot, Explore)

When touch top Hot and Explore, **Feed reload** with added Params to API:

- Following: `GET /api/v1/f/?type=following`
- Hot: `GET /api/v1/f/?type=hot`
- Explore: `GET /api/v1/f/?type=explore`

![image](https://user-images.githubusercontent.com/19923843/50952056-cbbeff80-14e1-11e9-85e6-ffd88772b4f7.png)

**Comment by kenz68** [comment]
2.Change new Top Navigator (Following, Hot, Explore)
duplicate with #103
